name: Update Angular UI Tokens

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.json'  # only trigger when tokens change

jobs:
  update-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout design tokens
        uses: actions/checkout@v4

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      # - name: Install dependencies
      #   run: npm install

      # - name: Generate SCSS from tokens
      #   run: npm run build-tokens
        # This should output SCSS files in ./dist or ./build directory

      - name: Clone Angular UI repo
        run: |
          git clone https://x-access-token:${{ secrets.ANGULAR_UI_DEPLOY_TOKEN }}@github.com/ashishsg444/ui.git
          cd ui
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      
      - name: Copy tokens into Angular repo
        run: |
          echo "ðŸ“‚ Current directory:"
          pwd

          echo "ðŸ—‚ Files here:"
          ls -R

          # make sure target folder exists
          mkdir -p ui/angular-git-int/tokens

          # copy the token JSON file from current repo into the Angular project
          cp core.json ui/angular-git-int/tokens/core.json

          echo "âœ… Files copied successfully!"


      - name: Commit and push changes
        run: |
          cd ui/angular-git-int

          # Configure Git user
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Create a new branch
          git checkout -b update-design-tokens-${{ github.run_id }}

          git add .
          git commit -m "chore: update design tokens from design-tokens repo" || echo "No changes to commit"

          # Update remote URL to use the deploy token
          git remote set-url origin https://x-access-token:${{ secrets.ANGULAR_UI_DEPLOY_TOKEN }}@github.com/ashishsg444/ui.git

          # Push using the token
          git push origin update-design-tokens-${{ github.run_id }}


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ANGULAR_UI_DEPLOY_TOKEN }}
          repository: ashishsg444/ui
          branch: update-design-tokens-${{ github.run_id }}
          title: "chore: update design tokens"
          body: "This PR updates SCSS tokens generated from the design-tokens repo."
          base: main
